#!/usr/bin/env pwsh
# Generates a WiX v4 fragment containing all files from the publish directory
param(
    [string]$PublishDir = "..\publish\VelocityShare.Server",
    [string]$OutputFile = "HarvestedFiles.wxs"
)

$publishPath = Resolve-Path $PublishDir -ErrorAction Stop
$components = [System.Text.StringBuilder]::new()
$componentRefs = [System.Text.StringBuilder]::new()
$guidCounter = 0

function New-DeterministicGuid($seed) {
    $hash = [System.Security.Cryptography.SHA256]::Create().ComputeHash(
        [System.Text.Encoding]::UTF8.GetBytes("VelocityShare-$seed")
    )
    $hex = [BitConverter]::ToString($hash[0..15]).Replace('-', '').ToLower()
    return "$($hex.Substring(0,8))-$($hex.Substring(8,4))-$($hex.Substring(12,4))-$($hex.Substring(16,4))-$($hex.Substring(20,12))"
}

function SanitizeId($name) {
    return $name -replace '[^a-zA-Z0-9_]', '_'
}

# Recursively enumerate all files (exclude files managed by Package.wxs)
$excludeFiles = @('VelocityShare.Server.exe')
$files = Get-ChildItem -Path $publishPath -Recurse -File |
    Where-Object { $excludeFiles -notcontains $_.Name } |
    Sort-Object FullName

foreach ($file in $files) {
    $relativePath = $file.FullName.Substring($publishPath.Path.Length + 1)
    $safeId = SanitizeId $relativePath
    $compId = "cmp_$safeId"
    $fileId = "fil_$safeId"
    $guid = New-DeterministicGuid $relativePath

    $null = $components.AppendLine("    <Component Id=`"$compId`" Guid=`"$guid`">")
    $null = $components.AppendLine("      <File Id=`"$fileId`" Source=`"..\publish\VelocityShare.Server\$($relativePath -replace '\\', '/')`" />")
    $null = $components.AppendLine("    </Component>")

    $null = $componentRefs.AppendLine("      <ComponentRef Id=`"$compId`" />")

    $guidCounter++
}

$wxs = @"
<!-- Auto-generated by generate-harvest.ps1 — do not edit manually -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <DirectoryRef Id="INSTALLFOLDER">
$components
    </DirectoryRef>
  </Fragment>
  <Fragment>
    <ComponentGroup Id="ServerFiles">
$componentRefs
    </ComponentGroup>
  </Fragment>
</Wix>
"@

# Fix: components need to be inside DirectoryRef, not flat
# Rebuild with proper directory nesting
$components = [System.Text.StringBuilder]::new()
$componentRefs = [System.Text.StringBuilder]::new()

# Group files by directory
$dirGroups = $files | Group-Object { $_.DirectoryName }

foreach ($group in $dirGroups) {
    $dirPath = $group.Name
    $relativeDir = if ($dirPath.Length -gt $publishPath.Path.Length) { $dirPath.Substring($publishPath.Path.Length + 1) } else { "" }

    if ([string]::IsNullOrEmpty($relativeDir)) {
        # Root files go directly in INSTALLFOLDER
        foreach ($file in $group.Group) {
            $relativePath = $file.Name
            $safeId = SanitizeId $relativePath
            $compId = "cmp_$safeId"
            $fileId = "fil_$safeId"
            $guid = New-DeterministicGuid $relativePath

            $null = $components.AppendLine("      <Component Id=`"$compId`" Guid=`"$guid`">")
            $null = $components.AppendLine("        <File Id=`"$fileId`" Source=`"$($file.FullName -replace '\\', '/')`" />")
            $null = $components.AppendLine("      </Component>")

            $null = $componentRefs.AppendLine("      <ComponentRef Id=`"$compId`" />")
        }
    } else {
        $dirId = "dir_" + (SanitizeId $relativeDir)
        $dirName = [System.IO.Path]::GetFileName($dirPath)

        $null = $components.AppendLine("    <Directory Id=`"$dirId`" Name=`"$dirName`">")

        foreach ($file in $group.Group) {
            $relativePath = $file.FullName.Substring($publishPath.Path.Length + 1)
            $safeId = SanitizeId $relativePath
            $compId = "cmp_$safeId"
            $fileId = "fil_$safeId"
            $guid = New-DeterministicGuid $relativePath

            $null = $components.AppendLine("      <Component Id=`"$compId`" Guid=`"$guid`">")
            $null = $components.AppendLine("        <File Id=`"$fileId`" Source=`"$($file.FullName -replace '\\', '/')`" />")
            $null = $components.AppendLine("      </Component>")

            $null = $componentRefs.AppendLine("      <ComponentRef Id=`"$compId`" />")
        }

        $null = $components.AppendLine("    </Directory>")
    }
}

$wxs = @"
<!-- Auto-generated by generate-harvest.ps1 — do not edit manually -->
<!-- Generated: $(Get-Date -Format 'o') — $guidCounter files -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <DirectoryRef Id="INSTALLFOLDER">
$components
    </DirectoryRef>
    <ComponentGroup Id="ServerFiles">
$componentRefs
    </ComponentGroup>
  </Fragment>
</Wix>
"@

$wxs | Out-File -FilePath $OutputFile -Encoding utf8
Write-Host "Generated $OutputFile with $guidCounter components"
